{{/*
app-service.yaml - RoboMindOS App Service
=============================================================================
*/}}
{{- if .Values.app.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "robomind.app.fullname" . }}
  labels:
    {{- include "robomind.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "robomind.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
{{- end }}
